modLoader = "javafml"
loaderVersion = "[47,)" # Adjust this based on your Forge version requirements
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayTest = "MATCH_VERSION"
acceptableRemoteVersions = "*"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_spellbooks"
mandatory = true
versionRange = "[${minecraft_version}-${irons_spells_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "geckolib"
mandatory = true
versionRange = "[${minecraft_version}:${geckolib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "curios"
mandatory = true
versionRange = "[${curios_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "caelus"
mandatory = true
versionRange = "[${caelus_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "playeranimator"
mandatory = true
versionRange = "[${player_animator_version},)"
ordering = "NONE"
side = "BOTH"
